// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ProjekatContext))]
    [Migration("20210107152418_D1")]
    partial class D1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataLayer.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("DataLayer.Models.Rec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Reci");
                });

            modelBuilder.Entity("DataLayer.Models.RecPoKategoriji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<int>("RecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("RecId");

                    b.ToTable("ReciPoKategorijama");
                });

            modelBuilder.Entity("DataLayer.Models.RecPoKategoriji", b =>
                {
                    b.HasOne("DataLayer.Models.Kategorija", "Kategorija")
                        .WithMany("ReciPoKategorijama")
                        .HasForeignKey("KategorijaId");

                    b.HasOne("DataLayer.Models.Rec", "Rec")
                        .WithMany("RecPoKategoriji")
                        .HasForeignKey("RecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Rec");
                });

            modelBuilder.Entity("DataLayer.Models.Kategorija", b =>
                {
                    b.Navigation("ReciPoKategorijama");
                });

            modelBuilder.Entity("DataLayer.Models.Rec", b =>
                {
                    b.Navigation("RecPoKategoriji");
                });
#pragma warning restore 612, 618
        }
    }
}
